apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHB6YmdodXl5
  CLOUDINARY_KEY: MTIzOTIyMTc4Mzg5NDMx
  CLOUDINARY_SECRET: cjJFaUFtQXB6ZHNIMHQxVThIcTdQMS11NllZ
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMmhoYVd0dGRYTjBZV1poTnpnaUxDSmhJam9pWTIxaGN6TXpiV1kyTUdnNWFESnJjMkUwZFdoamJqQnlaU0o5LlJZMjNvWmRvYmtQMk1NRTZDeVZxQ0E=
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjExMjJAY2x1c3RlcjAuZ3djbXp2by5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
